# Generated by Django 4.2.7 on 2023-11-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='injury_reserve',
            field=models.BooleanField(default=False),
        ),
    ]
